# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/binh/work/pulpino-binh/fpga/ips/bram_control/bram_control.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_emu_0/design_1_axi_gpio_emu_0.xci
# IP: The module: 'design_1_axi_gpio_emu_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/binh/work/pulpino-binh/fpga/ips/bram_control/bram_control.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_emu_0/design_1_axi_gpio_emu_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_emu_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/binh/work/pulpino-binh/fpga/ips/bram_control/bram_control.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_emu_0/design_1_axi_gpio_emu_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_emu_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/binh/work/pulpino-binh/fpga/ips/bram_control/bram_control.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_emu_0/design_1_axi_gpio_emu_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_emu_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/binh/work/pulpino-binh/fpga/ips/bram_control/bram_control.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_emu_0/design_1_axi_gpio_emu_0.xci
# IP: The module: 'design_1_axi_gpio_emu_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/binh/work/pulpino-binh/fpga/ips/bram_control/bram_control.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_emu_0/design_1_axi_gpio_emu_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_emu_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/binh/work/pulpino-binh/fpga/ips/bram_control/bram_control.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_emu_0/design_1_axi_gpio_emu_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_emu_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/binh/work/pulpino-binh/fpga/ips/bram_control/bram_control.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_emu_0/design_1_axi_gpio_emu_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_emu_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
